apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: default
data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: ecommerce_db
  DB_USER: root
  JWT_EXPIRATION_MS: "86400000"
